apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pv-claim
  labels:
    app: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels: 
        app: scraper
    spec:
      containers:
      - name: scraper
        image: kiote/scraper:1.0.3
        volumeMounts:
          - name: storage-pv-claim
            mountPath: /tmp
