version: "3"

networks:
  global:
    external: true

volumes:
  scraper-results:

services:  
  scraper:
    image: kiote/scraper:1.0.3
    environment:
      SEARCH_URL: https://eng.auto24.ee/kasutatud/nimekiri.php?bn=2&a=100&aj=&b=2&bw=2056&f1=2010&f2=2017&l2=110000&ae=2&af=50&ag=0&ag=1&otsi=search
    volumes:
      - scraper-results: /tmp
    networks:
      - global